[package]
name = "miden-assembly"
version = "0.8.0"
description = "Miden VM assembly language"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
documentation = "https://docs.rs/miden-assembly/0.8.0"
categories = ["compilers", "no-std"]
keywords = ["assembler", "assembly", "language", "miden"]
edition = "2021"
rust-version = "1.75"

[lib]
bench = false
doctest = false

[features]
default = ["std"]
std = ["vm-core/std", "miette/fancy"]

[dependencies]
num_enum = "0.7"
tracing = { version = "0.1", default-features = false, features = [
    "attributes",
] }
vm-core = { package = "miden-core", path = "../core", version = "0.8", default-features = false }

[target.'cfg(target_family = "wasm")'.dependencies]
miette = { git = "https://github.com/zkat/miette", rev = "328bf37", features = [
    "fancy-no-syscall",
] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
miette = { git = "https://github.com/zkat/miette", rev = "328bf37" }
