[package]
name = "miden-assembly"
version = "0.8.0"
description = "Miden VM assembly language"
authors = ["miden contributors"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/0xPolygonMiden/miden-vm"
documentation = "https://docs.rs/miden-assembly/0.8.0"
categories = ["compilers", "no-std"]
keywords = ["assembler", "assembly", "language", "miden"]
edition = "2021"
rust-version = "1.76"

[lib]
bench = false
doctest = false

[features]
default = ["std", "formatter"]
formatter = ["vm-core/formatter"]
std = [
    "aho-corasick/std",
    "vm-core/std",
    "miette/fancy",
    "thiserror/std",
    "miette/std",
]
testing = ["dep:regex"]

[dependencies]
aho-corasick = { version = "1.1", default-features = false }
lalrpop-util = { version = "0.20", default-features = false }
miette = { version = "7.1.0", git = "https://github.com/bitwalker/miette", branch = "no-std", default-features = false, features = [
    "fancy-no-syscall",
    "derive",
] }
regex = { version = "1.10", optional = true, default-features = false, features = [
    "unicode",
    "perf",
] }
smallvec = { version = "1.13", features = [
    "union",
    "const_generics",
    "const_new",
] }
tracing = { version = "0.1", default-features = false, features = [
    "attributes",
] }
thiserror = { version = "1.0", git = "https://github.com/bitwalker/thiserror", branch = "no-std", default-features = false }
unicode-width = { version = "0.1", features = ["no_std"] }
vm-core = { package = "miden-core", path = "../core", version = "0.8", default-features = false }

[dev-dependencies]
pretty_assertions = "1.4"
regex = { version = "1.10", default-features = false, features = [
    "unicode",
    "perf",
] }

[build-dependencies]
lalrpop = { version = "0.20", default-features = false }
rustc_version = "0.2"
